// "You might love this if..." lines, carried over from Bunny Trails' tree houses.
// They connect each career to something a 3 to 9 year old already enjoys.
const matches = {
  Astronaut: 'you love stars, planets and big adventures.',
  Astronomer: 'you love looking up at the moon and counting stars.',
  Paleontologist: 'you love dinosaurs and digging in the sandbox.',
  'Lab Scientist': 'you love asking "why?" and doing experiments.',
  'Heart Surgeon': 'you have careful hands and love helping people.',
  Pediatrician: 'you like taking care of babies, little kids and friends.',
  Nurse: 'you are kind, gentle and love helping people feel better.',
  Veterinarian: 'you love animals and like taking care of others.',
  Coder: 'you love puzzles and telling things exactly what to do.',
  'Video Game Designer': 'you love games and dreaming up new worlds.',
  'App Maker': 'you love tablets and have ideas for your own app.',
  'Robot Engineer': 'you love building things and making them move.',
  Inventor: 'you are always thinking of new ideas and never give up.',
  'Toy Designer': 'you love toys and making up new games to play.',
  Lawyer: 'you always speak up when something is not fair.',
  Judge: 'you are a great listener and like to be fair to everyone.',
  Journalist: 'you love asking questions and telling people what you found out.',
  'Podcast Host': 'you love talking, telling stories and making people laugh.',
  'Editor-in-Chief': 'you love books, magazines and being in charge.',
  'Mechanical Engineer': 'you love roller coasters and finding out how things work.',
  'Electrical Engineer': 'you love lights, buttons and things that beep.',
  'Biomedical Engineer': 'you love building things and helping people feel better.',
  'Civil Engineer': 'you love building bridges and towers with blocks.',
  Architect: 'you love drawing houses and building with blocks.',
  'Construction Worker': 'you love big trucks, tools and working as a team.',
  'Pop Star': 'you love singing, dancing and being on stage.',
  Dancer: 'you love music and can never sit still when a song comes on.',
  'Movie Director': 'you love movies and telling everyone where to stand.',
  'Orchestra Conductor': 'you love music and keeping everyone in rhythm.',
  'Head Chef': 'you love helping in the kitchen and tasting new foods.',
  Animator: 'you love cartoons and drawing your own characters.',
  CEO: 'you love being the leader and making big plans.',
  'Business Owner': 'you love playing store or running a lemonade stand.',
  'Fashion Brand Founder': 'you love picking outfits and designing your own clothes.',
  Banker: 'you love saving coins in your piggy bank.',
  Economist: 'you love numbers and figuring out how much things cost.',
  Firefighter: 'you are brave and love helping people stay safe.',
  Pilot: 'you love airplanes and looking out the window up high.',
  'Police Officer': 'you love helping people and keeping everyone safe.',
  Paramedic: 'you stay calm and love helping people in a hurry.',
  Mayor: 'you have big ideas to make your town a happier place.',
};

export function careerMatch(title) {
  return matches[title] ?? null;
}
